version: "3"

services:
  # php
  php:
    container_name: ${APP_NAME:-yuyama}_php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - ${PHP_PORT:-9001}:9000
      - ${VITE_PORT:-5173}:${VITE_PORT:-5173}  # Viteサーバー用のポートフォワーディング
    expose:
      - 9000
      - ${VITE_PORT:-5173}
    volumes:
      - ./src:/var/www/html
      - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.d/docker.conf
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/html
    command: sh -c "npm run dev & php-fpm"

  # web
  web:
    image: nginx
    container_name: ${APP_NAME:-yuyama}_web
    ports:
      - ${NGINX_PORT:-81}:80
    expose:
      - 80
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  # db
  db:
    platform: linux/x86_64
    image: mysql:8.0.33
    container_name: ${APP_NAME:-yuyama}_db
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    ports:
      - ${DB_PORT:-33061}:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/tmp:/var/lib/mysql

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${APP_NAME:-yuyama}_phpmyadmin
    ports:
      - ${PHPMYADMIN_PORT:-8010}:80
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      PMA_HOST: db
      MAX_EXECUTION_TIME: 3000
      MEMORY_LIMIT: 512M
      UPLOAD_LIMIT: 512M

  # mail
  mailhog:
    image: 'mailhog/mailhog:latest'
    container_name: ${APP_NAME:-yuyama}_mailhog
    ports:
      - ${FORWARD_MAILHOG_PORT:-1026}:1025
      - ${FORWARD_MAILHOG_DASHBOARD_PORT:-8026}:8025

  # redis
  redis:
    image: redis:7.2-rc2
    container_name: ${APP_NAME:-yuyama}_redis
    ports:
      - ${REDIS_PORT:-6380}:6379
    volumes:
      - ./docker/redis/data:/data

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: ${APP_NAME:-yuyama}_redisinsight
    ports:
      - ${REDISINSIGHT_PORT:-8003}:8001
    volumes:
      - ./docker/redisinsight:/db
    depends_on:
      - redis

  gcs:
    container_name: local-cloud-storage
    image: fsouza/fake-gcs-server:latest
    tty: true
    ports:
      - "4443:4443"
    volumes:
      - ./docker/gcs/data:/data
      - ./docker/gcs/storage:/storage
    command: -scheme http -public-host ${URL:-localhost}:4443

  ai:
    image: public.ecr.aws/a5k3r0e6/bonbon-test-ai:latest
    ports:
      - 8000:8000
      - 8501:8501